### ISSUE TITLE
Require citation information

### ISSUE THREAD

**Issue by duckontheweb** [radiantearth/geo-ml-model-catalog#6]
The `citation` field in the main model metadata document follows the [STAC Scientific Citation extension](https://github.com/stac-extensions/scientific), which requires that at least one of the fields (`doi`, `citation`, `publications`) must be specified. 

I'm opening this issue to discuss whether this requirement is sufficient for the GMLMC spec as well. Is requiring "at least one" of these fields enough? Do we need to specifically require any one field?

**Comment by HamedAlemo** [comment]
Models (as an object) can have a doi. The doi will naturally generate a citation for the model. So requiring a doi, means a citation should be provided as well. 
Publication is separate then the model doi. 

I suggest requiring doi and citation, and the publication be optional (high recommended). This will ensure that at model is version controlled similar to datasets.

**Comment by duckontheweb** [comment]
> I suggest requiring doi and citation, and the publication be optional (high recommended). This will ensure that at model is version controlled similar to datasets.

I'll open a PR to make both `doi` and `citation` required. 

> The doi will naturally generate a citation for the model. So requiring a doi, means a citation should be provided as well.

Perhaps we should we open an issue to enforce this in the Scientific Extension, as well. It seems like if it's universally true that the presence of a DOI means that a citation is possible then there might be interest in tightening that restriction.
